<?php

add_action( 'admin_menu', 'wpcs_add_admin_menu' );
add_action( 'admin_init', 'wpcs_settings_init' );

function wpcs_add_admin_menu(  ) {
    require_once(__DIR__ . '/govright.php');
    add_submenu_page('govright_options', 'GovRight Sitemap', 'Sitemap', 'manage_options', 'wpcs_options', 'wpcs_options_page');
}


function wpcs_settings_init(  ) {

    register_setting( 'wpcs_settings_page', 'wpcs_app' );

    add_settings_section(
        'wpcs_settings_page_section',
        __( '', 'wpcs' ),
        'wpcs_settings_page_section',
        'wpcs_settings_page'
    );

    add_settings_field(
        'wpcs_app',
        __( 'Application' ),
        'wpcs_app_render',
        'wpcs_settings_page',
        'wpcs_settings_page_section'
    );

    register_setting( 'wpcs_settings_page', 'wpcs_url_template' );

    add_settings_field(
        'wpcs_url_template',
        __( 'Article URL template' ),
        'wpcs_url_render',
        'wpcs_settings_page',
        'wpcs_settings_page_section'
    );

    register_setting( 'wpcs_settings_page', 'wpcs_law_slug' );

    add_settings_field(
        'wpcs_law_slug',
        __( 'Law slug' ),
        'wpcs_slug_render',
        'wpcs_settings_page',
        'wpcs_settings_page_section'
    );

    add_settings_section(
        'wpcs_settings_integration_section',
        __( '<a href="https://wordpress.org/plugins/google-sitemap-generator/" target="_blank">
            Google XML Sitemaps</a> plugin integration', 'wpcs' ),
        'wpcs_settings_integration_section',
        'wpcs_settings_page'
    );
}

function wpcs_settings_page_section() { ?>
    <?php if(wpcs_sitemap_exists()) { ?>
        Sitemap file has been generated and is avalable by this url:
        <a href="<?= wpcs_get_url() ?>" target="_blank"><?= wpcs_get_url() ?></a>
        <br>
        <button id="wpcs_remove" type="submit" class="button button-reset">Remove the sitemap file</button>
        <button id="wpcs_create" type="submit" class="button button-reset">Rebuild the sitemap file</button>
    <?php } else { ?>
        Sitemap file is missing, it was either removed or never generated.
        <br>
        <?php if(!get_option('wpcs_app') || !get_option('wpcs_url_template') || !get_option('wpcs_law_slug')) { ?>
            <button disabled class="button button-reset">Generate the sitemap file</button>
            <span style="position: relative; top: 5px; color: red;">
                Please specify GovRight <b>Application</b>, <b>Article URL template</b> and <b>Law slug</b> below.
            </span>
        <?php } else { ?>
            <button id="wpcs_create" type="submit" class="button button-reset">Generate the sitemap file</button>
        <?php } ?>
    <?php } ?>
    <img class="wpcs_spinner wpcs_spinner_create wpcs_spinner_remove" src="/wp-admin/images/spinner.gif" alt="">
<?php }

function wpcs_settings_integration_section() {
    $dep_plugin = wpcs_config('gxmls_dep');
    $dep_path = WP_CONTENT_DIR . '/plugins/' . $dep_plugin;
    if(!file_exists($dep_path)) {
        echo "Google XML Sitemaps plugin is not installed.";
        return;
    }
    if(!is_plugin_active($dep_plugin)) {
        echo "Google XML Sitemaps plugin is not activated.";
        return;
    }
    if(!wpcs_sitemap_exists()) {
        echo 'Sitemap file is missing, please generate the sitemap first. Then you\'ll be able to add it
        to the sitemap index generated by Google XML Sitemaps.';
        return;
    } ?>
    <?php if(wpcs_is_sitemap_in_gxmls()) { ?>
        Your sitemap has been added to the sitemap index generated by Google XML Sitemaps. <br>
        <button id="wpcs_gxmls_remove" class="button button-reset">Remove the sitemap from Google XML Sitemaps</button>
    <?php } else { ?>
        Add your sitemap file to the sitemap index generated by Google XML Sitemaps. <br>
        <button id="wpcs_gxmls_add" class="button button-reset">Add the sitemap to Google XML Sitemaps</button>
    <?php } ?>
    <img class="wpcs_spinner wpcs_spinner_gxmls_remove wpcs_spinner_gxmls_add" src="/wp-admin/images/spinner.gif" alt="">
<?php }

function wpcs_app_render()
{
    $app = get_option('wpcs_app');
    $apps = wpcs_config('apps'); ?>
    <select name="wpcs_app" style="width: 300px;">
        <option value="">Select an app</option>
        <?php foreach($apps as $slug => $name) { ?>
            <option value="<?php echo $slug; ?>" <?php selected($app, $slug); ?>><?php echo $name; ?></option>
        <?php } ?>
    </select>
    <?php
}

function wpcs_url_render()
{
    $tpl = get_option('wpcs_url_template'); ?>
    <input type="text" placeholder="http://example.com/#!/article={slug}" name="wpcs_url_template" value="<?php echo $tpl; ?>" style="width: 300px;">
    <?php
}


function wpcs_slug_render()
{
    $slug = get_option('wpcs_law_slug'); ?>
    <input type="text" name="wpcs_law_slug" value="<?php echo $slug; ?>" style="width: 300px;">
    <?php
}


function wpcs_options_page() { ?>
    <form action='options.php' method='post'>
        <h2>GovRight Sitemap</h2>
        <?php
        settings_fields( 'wpcs_settings_page' );
        do_settings_sections( 'wpcs_settings_page' );
        submit_button(); ?>
    </form>
    <style>
        .wpcs_spinner {
            display: none;
            position: relative;
            top: 5px;
            left: 5px;
        }
    </style>
<?php } ?>
